# Generated by Django 5.2.2 on 2025-06-08 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cash.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cash.type', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash.type', verbose_name='Тип'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'type')},
        ),
    ]
